get:
  operationId: get-project
  tags: [ projects ]
  summary: Get Project by code.
  description: |
    This method allows to retrieve a specific project.
  parameters:
    - $ref: '../parameters/Code.yaml'
  responses:
    200:
      description: A Project.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/Project.yaml'
    400:
      $ref: '../schemas/responses/ErrorShort400.yaml'
    401:
      $ref: '../schemas/responses/ErrorShort401.yaml'
    403:
      $ref: '../schemas/responses/ErrorShort403.yaml'
    404:
      $ref: '../schemas/responses/ErrorShort404.yaml'
    429:
      $ref: '../schemas/responses/ErrorShort429.yaml'

delete:
  operationId: delete-project
  tags: [ projects ]
  summary: Delete Project by code.
  description: |
    This method allows to delete a specific project.
  parameters:
    - $ref: '../parameters/Code.yaml'
  responses:
    200:
      description: A result of project removal.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/Base.yaml'
    400:
      $ref: '../schemas/responses/ErrorShort400.yaml'
    401:
      $ref: '../schemas/responses/ErrorShort401.yaml'
    403:
      $ref: '../schemas/responses/ErrorShort403.yaml'
    404:
      $ref: '../schemas/responses/ErrorShort404.yaml'
    429:
      $ref: '../schemas/responses/ErrorShort429.yaml'
