openapi: '3.0.0'

info:
  title: Qase.io API
  description: Qase API Specification.

  termsOfService: https://qase.io/terms
  version: 1.0.0

  contact:
    name: Qase.io
    url: https://qase.io
    email: support@qase.io

  license:
    name: Apache 2.0
    url: https://github.com/qase-tms/specs/blob/master/LICENSE

tags:
  - name: attachments
  - name: cases
  - name: custom-fields
  - name: environments
  - name: defects
  - name: plans
  - name: projects
  - name: results
  - name: milestones
  - name: runs
  - name: search
  - name: shared-steps
  - name: suites
  - name: users
#  - name: webhooks
#    description:
#      $ref: ./markdown/webhooks.md
#  - name: webhooks/Test case
#    description:
#      $ref: ./markdown/webhooks.case.md
#  - name: webhooks/Defect
#    description:
#      $ref: ./markdown/webhooks.defect.md
#  - name: webhooks/Custom field
#    description:
#      $ref: ./markdown/webhooks.field.md
#  - name: webhooks/Milestone
#    description:
#      $ref: ./markdown/webhooks.milestone.md
#  - name: webhooks/Test plan
#    description:
#      $ref: ./markdown/webhooks.plan.md
#  - name: webhooks/Test run
#    description:
#      $ref: ./markdown/webhooks.run.md
#  - name: webhooks/Shared step
#    description:
#      $ref: ./markdown/webhooks.step.md
#  - name: webhooks/suite
#    description:
#      $ref: ./markdown/webhooks.suite.md

servers:
  - url: https://api.qase.io/v1
    description: The production API server.
#  - url: https://dev.qase.io/v1
#    description: The development API server.

paths:
  /attachment:
    $ref: './paths/attachments.yaml'
  /attachment/{code|hash}:
    $ref: './paths/attachment.yaml'
  /case/{code}:
    $ref: './paths/cases.yaml'
  /case/{code}/{id}:
    $ref: './paths/case.yaml'
  /custom_field:
    $ref: './paths/custom_fields.yaml'
  /custom_field/{id}:
    $ref: './paths/custom_field.yaml'
  /defect/{code}:
    $ref: './paths/defects.yaml'
  /defect/{code}/{id}:
    $ref: './paths/defect.yaml'
  /defect/{code}/resolve/{id}:
    $ref: './paths/defect_resolve.yaml'
  /defect/{code}/status/{id}:
    $ref: './paths/defect_status.yaml'
  /environment/{code}:
    $ref: './paths/environments.yaml'
  /environment/{code}/{id}:
    $ref: './paths/environment.yaml'
  /milestone/{code}:
    $ref: './paths/milestones.yaml'
  /milestone/{code}/{id}:
    $ref: './paths/milestone.yaml'
  /plan/{code}:
    $ref: './paths/plans.yaml'
  /plan/{code}/{id}:
    $ref: './paths/plan.yaml'
  /project:
    $ref: './paths/projects.yaml'
  /project/{code}:
    $ref: './paths/project.yaml'
  /project/{code}/access:
    $ref: './paths/project_access.yaml'
  /result/{code}:
    $ref: './paths/results.yaml'
  /result/{code}/{id_or_hash}:
    $ref: './paths/result.yaml'
  /result/{code}/{id}/bulk:
    $ref: './paths/result_bulk.yaml'
  /result/{code}/{id}/{hash}:
    $ref: './paths/result_id_hash.yaml'
  /run/{code}:
    $ref: './paths/runs.yaml'
  /run/{code}/{id}:
    $ref: './paths/run.yaml'
  /run/{code}/{id}/public:
    $ref: './paths/run_public.yaml'
  /run/{code}/{id}/complete:
    $ref: './paths/run_complete.yaml'
  /search:
    $ref: './paths/search.yaml'
  /shared_step/{code}:
    $ref: './paths/shared_steps.yaml'
  /shared_step/{code}/{hash}:
    $ref: './paths/shared_step.yaml'
  /suite/{code}:
    $ref: './paths/suites.yaml'
  /suite/{code}/{id}:
    $ref: './paths/suite.yaml'
  /user:
    $ref: './paths/users.yaml'
  /user/{id}:
    $ref: './paths/user.yaml'

components:
  schemas:
    Attachment: { $ref: './schemas/Attachment.yaml' }
    AttachmentGet: { $ref: './schemas/Attachment.get.yaml' }
    AttachmentHash: { $ref: './schemas/Attachment.hash.yaml' }
    AttachmentHashList: { $ref: './schemas/Attachment.hash_list.yaml' }
    CustomField: { $ref: './schemas/CustomField.yaml' }
    CustomFieldCreate: { $ref: './schemas/CustomField.create.yaml' }
    CustomFieldUpdate: { $ref: './schemas/CustomField.update.yaml' }
    CustomFieldValue: { $ref: './schemas/CustomFieldValue.yaml' }
    Defect: { $ref: './schemas/Defect.yaml' }
    DefectCreate: { $ref: './schemas/Defect.create.yaml' }
    DefectStatus: { $ref: './schemas/Defect.status.yaml' }
    DefectUpdate: { $ref: './schemas/Defect.update.yaml' }
    Environment: { $ref: './schemas/Environment.yaml' }
    EnvironmentCreate: { $ref: './schemas/Environment.create.yaml' }
    EnvironmentUpdate: { $ref: './schemas/Environment.update.yaml' }
    Milestone: { $ref: './schemas/Milestone.yaml' }
    MilestoneCreate: { $ref: './schemas/Milestone.create.yaml' }
    MilestoneUpdate: { $ref: './schemas/Milestone.update.yaml' }
    Plan: { $ref: './schemas/Plan.yaml' }
    PlanCreate: { $ref: './schemas/Plan.create.yaml' }
    PlanDetailed: { $ref: './schemas/Plan.detailed.yaml' }
    PlanUpdate: { $ref: './schemas/Plan.update.yaml' }
    Project: { $ref: './schemas/Project.yaml' }
    ProjectAccess: { $ref: './schemas/Project.access.yaml' }
    ProjectCreate: { $ref: './schemas/Project.create.yaml' }
    Result: { $ref: './schemas/Result.yaml' }
    ResultCreate: { $ref: './schemas/Result.create.yaml' }
    ResultCreateBulk: { $ref: './schemas/Result.create_bulk.yaml' }
    ResultUpdate: { $ref: './schemas/Result.update.yaml' }
    Run: { $ref: './schemas/Run.yaml' }
    RunCreate: { $ref: './schemas/Run.create.yaml' }
    RunPublic: { $ref: './schemas/Run.public.yaml' }
    Requirement: { $ref: './schemas/Requirement.yaml' }
    SharedStep: { $ref: './schemas/SharedStep.yaml' }
    SharedStepCreate: { $ref: './schemas/SharedStep.create.yaml' }
    SharedStepUpdate: { $ref: './schemas/SharedStep.update.yaml' }
    Suite: { $ref: './schemas/Suite.yaml' }
    SuiteCreate: { $ref: './schemas/Suite.create.yaml' }
    SuiteDelete: { $ref: './schemas/Suite.delete.yaml' }
    TagValue: { $ref: './schemas/Tag.value.yaml' }
    TestCase: { $ref: './schemas/TestCase.yaml' }
    TestCaseCreate: { $ref: './schemas/TestCase.create.yaml' }
    TestCaseUpdate: { $ref: './schemas/TestCase.update.yaml' }
    TestStep: { $ref: './schemas/TestStep.yaml' }
    User: { $ref: './schemas/User.yaml' }

    AttachmentResponse: { $ref: './schemas/responses/Attachment.yaml' }
    AttachmentListResponse: { $ref: './schemas/responses/AttachmentList.yaml' }
    AttachmentUploadsResponse: { $ref: './schemas/responses/AttachmentUploads.yaml' }
    CustomFieldResponse: { $ref: './schemas/responses/CustomField.yaml' }
    CustomFieldsResponse: { $ref: './schemas/responses/CustomFieldList.yaml' }
    DefectResponse: { $ref: './schemas/responses/Defect.yaml' }
    DefectListResponse: { $ref: './schemas/responses/DefectList.yaml' }
    EnvironmentResponse: { $ref: './schemas/responses/Environment.yaml' }
    EnvironmentListResponse: { $ref: './schemas/responses/EnvironmentList.yaml' }
    IdResponse: { $ref: './schemas/responses/Id.yaml' }
    HashResponse: { $ref: './schemas/responses/Hash.yaml' }
    MilestoneResponse: { $ref: './schemas/responses/Milestone.yaml' }
    MilestoneListResponse: { $ref: './schemas/responses/MilestoneList.yaml' }
    PlanResponse: { $ref: './schemas/responses/Plan.yaml' }
    PlanListResponse: { $ref: './schemas/responses/PlanList.yaml' }
    ProjectResponse: { $ref: './schemas/responses/Project.yaml' }
    ProjectCodeResponse: { $ref: './schemas/responses/ProjectCode.yaml' }
    ProjectListResponse: { $ref: './schemas/responses/ProjectList.yaml' }
    Response: { $ref: './schemas/responses/Base.yaml' }
    ResultResponse: { $ref: './schemas/responses/Result.yaml' }
    ResultListResponse: { $ref: './schemas/responses/ResultList.yaml' }
    RunResponse: { $ref: './schemas/responses/Run.yaml' }
    RunListResponse: { $ref: './schemas/responses/RunList.yaml' }
    RunPublicResponse: { $ref: './schemas/responses/RunPublic.yaml' }
    SearchResponse: { $ref: './schemas/responses/Search.yaml' }
    SharedStepResponse: { $ref: './schemas/responses/SharedStep.yaml' }
    SharedStepListResponse: { $ref: './schemas/responses/SharedStepList.yaml' }
    SuiteResponse: { $ref: './schemas/responses/Suite.yaml' }
    SuiteListResponse: { $ref: './schemas/responses/SuiteList.yaml' }
    TestCaseResponse: { $ref: './schemas/responses/TestCase.yaml' }
    TestCaseListResponse: { $ref: './schemas/responses/TestCaseList.yaml' }
    UserResponse: { $ref: './schemas/responses/User.yaml' }
    UserListResponse: { $ref: './schemas/responses/UserList.yaml' }

  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Token

  parameters:
    Code: { $ref: './parameters/Code.yaml' }
    ExtendRuns: { $ref: './parameters/extend/Runs.yaml' }
    FilterCases: { $ref: './parameters/filter/Cases.yaml' }
    FilterCustomFields: { $ref: './parameters/filter/CustomFields.yaml' }
    FilterDefects: { $ref: './parameters/filter/Defects.yaml' }
    FilterMilestones: { $ref: './parameters/filter/Milestones.yaml' }
    FilterResults: { $ref: './parameters/filter/Results.yaml' }
    FilterRuns: { $ref: './parameters/filter/Runs.yaml' }
    FilterSharedSteps: { $ref: './parameters/filter/SharedSteps.yaml' }
    FilterSuites: { $ref: './parameters/filter/Suites.yaml' }
    Hash: { $ref: './parameters/Hash.yaml' }
    Id: { $ref: './parameters/Id.yaml' }
    IdOrHash: { $ref: './parameters/IdOrHash.yaml' }
    Limit: { $ref: './parameters/pagination/Limit.yaml' }
    Offset: { $ref: './parameters/pagination/Offset.yaml' }

security:
  - TokenAuth: []
