#!/usr/bin/env bash

set -o nounset
set -o pipefail

function build() {
  npm run test
}

function go() {
  rm -rf examples/sdk/*
  docker run --rm -it \
    -v "$(pwd)"/examples/sdk/go:/sdk \
    -v "$(pwd)"/api.yaml:/specs/api.yaml \
    swaggerapi/swagger-codegen-cli-v3 \
    generate -i /specs/api.yaml -l go -o /sdk -D packageName=qase
  goimports -ungroup -local qase -w ./examples/sdk/go/
}

function ui() {
  docker run --rm -it \
    -e SWAGGER_JSON=/specs/api.yaml \
    -p 8080:8080 \
    -v "$(pwd)"/api.yaml:/specs/api.yaml \
    swaggerapi/swagger-ui
}

__default() { help; }

"${@:-__default}"
