#!/usr/bin/env bash

set -o nounset
set -o pipefail

function build() {
  npm run test
}

function ui() {
  docker run --rm -it \
    -e SWAGGER_JSON=/specs/api.yaml \
    -p 8080:8080 \
    -v "$(pwd)"/api.yaml:/specs/api.yaml \
    swaggerapi/swagger-ui
}

function go() {
  docker run --rm -it \
    -v "$(pwd)"/examples/sdk:/sdk \
    -v "$(pwd)"/api.json:/specs/api.json \
    --entrypoint=sh \
    swaggerapi/swagger-codegen-cli
#    generate -i /specs/api.json -l go -o /sdk -DpackageName=qase
}

__default() { help; }

"${@:-__default}"
