# operationId: get-custom-fields
GET {{host}}/custom_field?filters[type]=url
Token: {{token}}
Content-Type: application/json
###

# operationId: create-custom-field
POST {{host}}/custom_field
Token: {{token}}
Content-Type: application/json

{
    "entity": 0,
    "type": 0,
    "title": "new title",
    "projects_codes": ["DEMO"]
}
###

# operationId: get-custom-field
GET {{host}}/custom_field/1
Token: {{token}}
Content-Type: application/json
###

# operationId: delete-custom-field
DELETE {{host}}/custom_field/1
Token: {{token}}
Content-Type: application/json
###

# operationId: update-custom-field
PATCH {{host}}/custom_field/1
Token: {{token}}
Content-Type: application/json

{
    "title": "new title",
    "projects_codes": ["DEMO"]
}
###
