post:
  operationId: create-configuration-group
  tags: [ configurations ]
  summary: Create a new configuration group.
  description: |
    This method allows to create a configuration group in selected project.

  parameters:
    - $ref: '../parameters/Code.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/ConfigurationGroup.create.yaml'

  responses:
    200:
      description: A result.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/IdResponse.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    422:
      description: Unprocessable Entity.
    429:
      description: Too Many Requests.
