get:
  operationId: get-configurations
  tags: [ configurations ]
  summary: Get all configuration groups with configurations.
  description: |
    This method allows to retrieve all configurations groups with configurations

  parameters:
    - $ref: '../parameters/Code.yaml'

  responses:
    200:
      description: A list of all configurations.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/ConfigurationListResponse.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    429:
      description: Too Many Requests.

post:
  operationId: create-configuration
  tags: [ configurations ]
  summary: Create a new configuration in a particular group.
  description: |
    This method allows to create a configuration in selected project.

  parameters:
    - $ref: '../parameters/Code.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Configuration.create.yaml'

  responses:
    200:
      description: A result.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/IdResponse.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    422:
      description: Unprocessable Entity.
    429:
      description: Too Many Requests.
