get:
  operationId: get-project
  tags: [ projects ]
  summary: Get Project by code.
  description: |
    This method allows to retrieve a specific project.
  parameters:
    - $ref: '../parameters/Code.yaml'
  responses:
    200:
      description: A Project.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/ProjectResponse.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    429:
      description: Too Many Requests.

delete:
  operationId: delete-project
  tags: [ projects ]
  summary: Delete Project by code.
  description: |
    This method allows to delete a specific project.
  parameters:
    - $ref: '../parameters/Code.yaml'
  responses:
    200:
      description: A result of project removal.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/BaseResponse.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    429:
      description: Too Many Requests.
