openapi: '3.0.0'

info:
  title: Qase.io TestOps API v2
  description: Qase TestOps API v2 Specification.

  termsOfService: https://qase.io/terms
  version: 2.0.0

  contact:
    name: Qase.io
    url: https://qase.io
    email: support@qase.io

  license:
    name: Apache 2.0
    url: https://github.com/qase-tms/specs/blob/master/LICENSE

tags:
  - name: attachments
  - name: authors
  - name: cases
  - name: custom-fields
  - name: environments
  - name: defects
  - name: plans
  - name: projects
  - name: results
  - name: milestones
  - name: runs
  - name: search
  - name: shared-steps
  - name: suites

servers:
  - url: https://api.qase.io/v2
    description: The production API server.

paths:
  /{project_code}/run/{run_id}/result:
    $ref: './paths/v2/result.yaml'

components:
  schemas:
    # new results api
    ResultStep: { $ref: './schemas/v2/ResultStep.yaml' }
    ResultAttachment: { $ref: './schemas/v2/ResultAttachment.yaml' }
    ResultExecution: { $ref: './schemas/v2/ResultExecution.yaml' }
    ResultStepExecution: { $ref: './schemas/v2/ResultStepExecution.yaml' }
    ResultRelations: { $ref: './schemas/v2/ResultRelations.yaml' }
    ResultStatus: { $ref: './schemas/v2/ResultStatus.yaml' }

  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Token

  parameters:
    Code: { $ref: './parameters/Code.yaml' }
    ExtendRuns: { $ref: './parameters/extend/Runs.yaml' }
    Hash: { $ref: './parameters/Hash.yaml' }
    Id: { $ref: './parameters/Id.yaml' }
    Limit: { $ref: './parameters/pagination/Limit.yaml' }
    Offset: { $ref: './parameters/pagination/Offset.yaml' }

security:
  - TokenAuth: []
