#!/usr/bin/env bash

set -o nounset
set -o pipefail
set -o errexit

### shortcut

function validate() {
  npm run validate
}

### codegen

function go() {
  local version=${1:-v1}

  rm -rf "${version}/sdk/go/*"
  openapi generate -i /specs/src.yaml -g go -o sdk/go -c /sdk/go.yml "${version}"
  goimports -local qase -w "${version}/sdk/go/"
}

function php() {
  local version=${1:-v1}

  rm -rf "${version}/sdk/php"
  mkdir "${version}/sdk/php"
  cp "${version}/sdk/templates/php-openapi-generator-ignore" "${version}/sdk/php/.openapi-generator-ignore"
  openapi generate -i /specs/src.yaml -g php -o sdk/php -c sdk/php.yml "${version}"
}

function typescript() {
  local version=${1:-v1}

  rm -rf "${version}/sdk/ts"
  mkdir "${version}/sdk/ts"
  cp "${version}/sdk/templates/ts-openapi-generator-ignore" "${version}/sdk/ts/.openapi-generator-ignore"
  openapi generate -i /specs/src.yaml -g typescript-axios -t sdk/templates/axios -o sdk/ts -c sdk/ts.yml --additional-properties=npmName=qaseio "${version}"
}

function python() {
  local version=${1:-v1}

  rm -rf "${version}/sdk/python"
  mkdir -p "${version}/sdk/python"
  cp "${version}/sdk/templates/python-openapi-generator-ignore" "${version}/sdk/python/.openapi-generator-ignore"
  openapi generate -i /specs/src.yaml -g python -t sdk/templates -o sdk/python --additional-properties=packageName=qaseio "${version}"
}

function openapi() {
  local version=${@: -1}  # Get the last argument
  local args=("${@}")  # Copy the arguments array
  unset args[-1]  # Remove the last element (version) from args

  if [[ "$version" != "v1" && "$version" != "v2" ]]; then
    echo "Error: Invalid version. Only 'v1' or 'v2' are accepted."
    return 1
  fi

  docker run --rm -i \
    -v "$(pwd)/${version}/paths:/specs/paths" \
    -v "$(pwd)/${version}/schemas:/specs/schemas" \
    -v "$(pwd)/${version}/parameters:/specs/parameters" \
    -v "$(pwd)/${version}/src.yaml:/specs/src.yaml" \
    -v "$(pwd)/${version}/sdk:/sdk" \
    openapitools/openapi-generator-cli:v7.2.0 "${args[@]}"
}

__default() { help; }

"${@:-__default}"
