#!/usr/bin/env bash

set -o nounset
set -o pipefail

### shortcut

function validate() {
  npm run validate
}

### codegen

function go() {
  rm -rf sdk/go/*
  openapi generate -i /specs/src.yaml -g go -o sdk/go -c sdk/go.yml
  goimports -ungroup -local qase -w sdk/go/
}

function php() {
  rm -rf sdk/php
  mkdir sdk/php
  cp sdk/templates/php-openapi-generator-ignore sdk/php/.openapi-generator-ignore
  openapi generate -i /specs/src.yaml -g php -o sdk/php -c sdk/php.yml
}

function typescript() {
  rm -rf sdk/ts
  mkdir sdk/ts
  cp sdk/templates/ts-openapi-generator-ignore sdk/ts/.openapi-generator-ignore
  openapi generate -i /specs/src.yaml -g typescript-axios -t /sdk/templates/axios -o /sdk/ts -c /sdk/ts.yml --additional-properties=npmName=qaseio
}

function python() {
  rm -rf sdk/python
  mkdir sdk/python
  cp sdk/templates/python-openapi-generator-ignore sdk/python/.openapi-generator-ignore
  openapi generate -i /specs/src.yaml -g python -o sdk/python --additional-properties=packageName=qaseio,packageUrl=https://github.com/qase-tms/qase-python
}

openapi() {
  # https://github.com/OpenAPITools/openapi-generator-cli
  docker run --rm -i \
    -v "$(pwd)"/paths:/specs/paths \
    -v "$(pwd)"/schemas:/specs/schemas \
    -v "$(pwd)"/parameters:/specs/parameters \
    -v "$(pwd)"/src.yaml:/specs/src.yaml \
    -v "$(pwd)"/sdk:/sdk \
    openapitools/openapi-generator-cli:v6.4.0 "${@}"
}

__default() { help; }

"${@:-__default}"
