/**
 * Qase.io API
 * You can use our API to access Qase.io API endpoints, which allows to retrieve information about entities stored in database and perform actions with them. The API is organized around REST. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("ProjectsApi", () => {
  let instance: api.ProjectsApi
  beforeEach(function() {
    instance = new api.ProjectsApi(config)
  });

  test("projectList", () => {
    const limit: number = 56
    const offset: number = 56
    return expect(instance.projectList(limit, offset, {})).resolves.toBe(null)
  })
})

